# Leaf01 IF Datei

- hosts: leaf01
  name: Interfaces for Leaf01
  become: yes
  gather_facts: no
  tasks:
    - name: layer 2 evpn
      copy: 
        src: /home/cumulus/ON-07/leaf01-if-04 
        dest: /etc/network/interfaces
    # aktivieren
    - name: Activate changes
      shell: /sbin/ifreload -a
      
# #################################################################    
    
# Leaf02 IF Datei

- hosts: leaf02
  name: Interfaces for Leaf02
  become: yes
  gather_facts: no
  tasks:
    - name: layer 2 evpn
      copy: 
        src: /home/cumulus/ON-07/leaf02-if-04
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes
      shell: /sbin/ifreload -a    
    
